// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRequestToCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRequestToCollection'](arg1, arg2, arg3);
}

export function AppDataDir() {
  return window['go']['main']['App']['AppDataDir']();
}

export function CancelRequest() {
  return window['go']['main']['App']['CancelRequest']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function CreateWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteSavedRequest(arg1) {
  return window['go']['main']['App']['DeleteSavedRequest'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function GetActiveWorkspace() {
  return window['go']['main']['App']['GetActiveWorkspace']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function ImportPostman(arg1, arg2) {
  return window['go']['main']['App']['ImportPostman'](arg1, arg2);
}

export function OpenWorkspaceFromFolder(arg1) {
  return window['go']['main']['App']['OpenWorkspaceFromFolder'](arg1);
}

export function PickFile(arg1, arg2) {
  return window['go']['main']['App']['PickFile'](arg1, arg2);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function ReadFileText(arg1) {
  return window['go']['main']['App']['ReadFileText'](arg1);
}

export function RelocateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RelocateWorkspace'](arg1, arg2);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}

export function UpdateEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1, arg2, arg3);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function UpdateSavedRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSavedRequest'](arg1, arg2, arg3);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function InitGit(arg1, arg2) {
  return window['go']['main']['App']['InitGit'](arg1, arg2);
}

export function CommitAndPush(arg1) {
  return window['go']['main']['App']['CommitAndPush'](arg1);
}

export function GitPull() {
  return window['go']['main']['App']['GitPull']();
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function SwitchBranch(arg1) {
  return window['go']['main']['App']['SwitchBranch'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function GetGitLog(arg1) {
  return window['go']['main']['App']['GetGitLog'](arg1);
}

export function LockCollection(arg1) {
  return window['go']['main']['App']['LockCollection'](arg1);
}

export function UnlockCollection(arg1) {
  return window['go']['main']['App']['UnlockCollection'](arg1);
}

export function GetLocks() {
  return window['go']['main']['App']['GetLocks']();
}
