// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {environments} from '../models';

export function AddRequestToCollection(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<models.SavedRequest>;

export function ClearHistory():Promise<void>;

export function CreateCollection(arg1:string):Promise<models.Collection>;

export function CreateEnvironment(arg1:string):Promise<models.Environment>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteSavedRequest(arg1:string):Promise<void>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetEnvironments():Promise<environments.Snapshot>;

export function GetHistory():Promise<Array<models.HistoryEntry>>;

export function ImportPostman(arg1:string,arg2:string):Promise<number>;

export function PickFile(arg1:string,arg2:string):Promise<string>;

export function ReadFileText(arg1:string):Promise<string>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function SendRequest(arg1:models.RequestPayload):Promise<models.ResponseResult>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function UpdateEnvironment(arg1:string,arg2:string,arg3:Array<models.EnvVar>):Promise<void>;

export function UpdateSavedRequest(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<void>;
