// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {workspaces} from '../models';
import {environments} from '../models';
import {profile} from '../models';

export function AddRequestToCollection(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<models.SavedRequest>;

export function AppDataDir():Promise<string>;

export function CancelRequest():Promise<void>;

export function ClearHistory():Promise<void>;

export function CreateCollection(arg1:string):Promise<models.Collection>;

export function CreateEnvironment(arg1:string):Promise<models.Environment>;

export function CreateWorkspace(arg1:string,arg2:string,arg3:string):Promise<workspaces.Info>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteSavedRequest(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetActiveWorkspace():Promise<workspaces.Info>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetEnvironments():Promise<environments.Snapshot>;

export function GetHistory():Promise<Array<models.HistoryEntry>>;

export function GetProfile():Promise<profile.Profile>;

export function GetWorkspaces():Promise<Array<workspaces.Info>>;

export function ImportPostman(arg1:string,arg2:string):Promise<number>;

export function OpenWorkspaceFromFolder(arg1:string):Promise<workspaces.Info>;

export function PickFile(arg1:string,arg2:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function ReadFileText(arg1:string):Promise<string>;

export function RelocateWorkspace(arg1:string,arg2:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<void>;

export function SendRequest(arg1:models.RequestPayload):Promise<models.ResponseResult>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<workspaces.Info>;

export function UpdateEnvironment(arg1:string,arg2:string,arg3:Array<models.EnvVar>):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string):Promise<void>;

export function UpdateSavedRequest(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<void>;

export function GetGitStatus():Promise<{initialised:boolean,hasChanges:boolean,currentBranch:string,remoteUrl:string}>;

export function InitGit(arg1:string,arg2:string):Promise<void>;

export function CommitAndPush(arg1:string):Promise<void>;

export function GitPull():Promise<void>;

export function GetBranches():Promise<Array<string>>;

export function SwitchBranch(arg1:string):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function GetGitLog(arg1:number):Promise<Array<{hash:string,message:string,author:string,when:string}>>;

export function LockCollection(arg1:string):Promise<void>;

export function UnlockCollection(arg1:string):Promise<void>;

export function GetLocks():Promise<Record<string,{user:string,email:string,since:string}>>;
