// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {updater} from '../models';
import {workspaces} from '../models';
import {git} from '../models';
import {cookies} from '../models';
import {environments} from '../models';
import {main} from '../models';
import {locks} from '../models';
import {profile} from '../models';

export function AddRequestToCollection(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<models.SavedRequest>;

export function AppDataDir():Promise<string>;

export function CancelRequest():Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function ClearAllCookies():Promise<void>;

export function ClearCookiesForDomain(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function CommitAndPush(arg1:string):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function CreateCollection(arg1:string):Promise<models.Collection>;

export function CreateEnvironment(arg1:string):Promise<models.Environment>;

export function CreateWorkspace(arg1:string,arg2:string,arg3:string):Promise<workspaces.Info>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteSavedRequest(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetActiveContributors():Promise<Array<git.Contributor>>;

export function GetActiveWorkspace():Promise<workspaces.Info>;

export function GetBranches():Promise<Array<string>>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetCookies():Promise<Array<cookies.CookieInfo>>;

export function GetEnvironments():Promise<environments.Snapshot>;

export function GetGitLog(arg1:number):Promise<Array<git.CommitInfo>>;

export function GetGitStatus():Promise<main.GitStatus>;

export function GetHistory():Promise<Array<models.HistoryEntry>>;

export function GetLocks():Promise<Record<string, locks.LockInfo>>;

export function GetMockStatus():Promise<main.MockStatus>;

export function GetProfile():Promise<profile.Profile>;

export function GetVersion():Promise<string>;

export function GetWorkspaces():Promise<Array<workspaces.Info>>;

export function GitPull():Promise<void>;

export function ImportPostman(arg1:string,arg2:string):Promise<number>;

export function InitGit(arg1:string,arg2:string):Promise<void>;

export function InvalidateSpec(arg1:string):Promise<void>;

export function LinkCollectionSpec(arg1:string,arg2:string):Promise<void>;

export function LockCollection(arg1:string):Promise<void>;

export function OpenWorkspaceFromFolder(arg1:string):Promise<workspaces.Info>;

export function PickFile(arg1:string,arg2:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function ReadFileText(arg1:string):Promise<string>;

export function RelocateWorkspace(arg1:string,arg2:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<void>;

export function RunCollection(arg1:Array<models.RunnerRequest>,arg2:Record<string, models.Assertion>):Promise<models.CollectionRunResult>;

export function SaveCapturedResponse(arg1:string,arg2:string,arg3:models.SavedResponse):Promise<void>;

export function SaveResponseToRequest(arg1:string,arg2:string):Promise<void>;

export function SendRequest(arg1:models.RequestPayload):Promise<models.ResponseResult>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function SetRouteOverride(arg1:string,arg2:string,arg3:models.MockOverride):Promise<void>;

export function StartMockServer(arg1:number):Promise<main.MockStatus>;

export function StopMockServer():Promise<void>;

export function SwitchBranch(arg1:string):Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<workspaces.Info>;

export function UnlockCollection(arg1:string):Promise<void>;

export function UpdateEnvironment(arg1:string,arg2:string,arg3:Array<models.EnvVar>):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string):Promise<void>;

export function UpdateSavedRequest(arg1:string,arg2:string,arg3:models.RequestPayload):Promise<void>;
