package tray

// This package is a thin abstraction over the Wails runtime for system tray,
// notifications, and background execution. It is a no-op stub for headless/CI
// environments and delegates to Wails when the runtime context is available.

import (
	"context"
	"fmt"
	"sync"

	"github.com/wailsapp/wails/v2/pkg/runtime"
)

// Tray manages the system tray icon, context menu, and notifications.
type Tray struct {
	ctx    context.Context
	mu     sync.Mutex
	active bool
}

// New creates a tray manager. Call SetContext before any runtime calls.
func New() *Tray {
	return &Tray{}
}

// SetContext wires the Wails runtime context.
func (t *Tray) SetContext(ctx context.Context) {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.ctx = ctx
}

// Setup creates the system tray icon and context menu.
func (t *Tray) Setup() {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.ctx == nil {
		return
	}
	t.active = true
	runtime.MenuSetApplicationMenu(t.ctx, nil)
}

// ShowNotification sends a desktop notification via Wails runtime.
func (t *Tray) ShowNotification(title, message string) {
	t.mu.Lock()
	ctx := t.ctx
	t.mu.Unlock()
	if ctx == nil {
		return
	}
	runtime.EventsEmit(ctx, "notification:show", title, message)
}

// IsActive returns whether the tray has been set up.
func (t *Tray) IsActive() bool {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.active
}

// CLIRunnerTemplate returns a cross-platform shell script snippet
// for executing a single collection from the command line.
func CLIRunnerTemplate(binaryPath, workspaceDir, collectionName string) string {
	return fmt.Sprintf(`#!/bin/sh
# reqit CLI runner — generated by reqit
# Usage: sh %s.sh [--env <name>] [--output text|json]
REQIT_BIN="%s"
WORKSPACE="%s"
COLLECTION="%s"
if [ "$1" = "--help" ]; then
	echo "Usage: $0 [--env <name>] [--output text|json]"
	exit 0
fi
"$REQIT_BIN" run "$COLLECTION" --workspace "$WORKSPACE" "$@"
`, sanitizeName(collectionName), binaryPath, workspaceDir, collectionName)
}

func sanitizeName(name string) string {
	output := make([]byte, 0, len(name))
	for _, ch := range []byte(name) {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') || ch == '-' || ch == '_' {
			output = append(output, ch)
		} else {
			output = append(output, '_')
		}
	}
	return string(output)
}
